### ISSUE TITLE
Brazilian podcasts (pt-br content)

### ISSUE THREAD

**Issue by avelino** [rShetty/awesome-podcasts#103]
- http://pca.st/podcast/4b917750-c034-0135-9e60-5bb073f92b78
- http://pca.st/podcast/8c92b8c0-2f51-0134-eba6-0d50f522381b
- http://pca.st/podcast/851f3be0-ed73-012e-e0aa-525400c11844
- http://pca.st/podcast/2c13caf0-f08d-0133-9c6b-59d98c6b72b8
- http://pca.st/podcast/bb7ad240-0938-0135-ecad-4114446340cb
- http://pca.st/podcast/423c20f0-e75d-0132-0d24-059c869cc4eb
- http://pca.st/podcast/79fa5f80-0b13-0135-ecbb-4114446340cb
- http://pca.st/podcast/c396f4f0-aa43-012e-5976-00163e1b201c

**Comment by saitonakamura** [comment]
@avelino is brazilian portuguese much different from portugal portuguese? To put a question in a different way, can portugal people listen to brazilian podcasts and visa versa. If yes, can you please create a PR which add a new file `PT.md` (if not `PT-BR.md` will do I think) and place this podcasts there along with description and frequencies?
