### ISSUE TITLE
[Suggestion] Adding Contribution guidelines

### ISSUE THREAD

**Issue by skat00sh** [rShetty/awesome-podcasts#114]
There is no contributing.md yet, might be useful though.

**Comment by rShetty** [comment]
Hmm I think it will be useful. Currently it is part of pull_request_template. Can you help raise a PR for this. Thanks.

**Comment by skat00sh** [comment]
Sure! will do it

**Comment by skat00sh** [comment]
Should I submit a PR with the same set of instructions as in pull_request_template as of now or you have some suggestions to add to it?

**Comment by rShetty** [comment]
@skat00sh For now it should be fine
