### ISSUE TITLE
[Suggestion] Listing Repo in Awesome Lists

### ISSUE THREAD

**Issue by skat00sh** [rShetty/awesome-podcasts#119]
I just raised an issue in the [awesome](https://github.com/sindresorhus/awesome) repo asking to add this repo to their list. You could check it [here](https://github.com/sindresorhus/awesome/issues/1288)
The owner suggested a couple of things to be checked like adding a few tags etc. 
Would you like this repo to be featured there?

**Comment by rShetty** [comment]
@skat00sh yes it should. thanks for this

**Comment by rShetty** [comment]
@skat00sh yes it should. thanks for this. Can you help raise appropriate PR ? I can help with tags and other things

**Comment by skat00sh** [comment]
@rShetty PR is done for awesome-badge
Please add the following tags to the topic -> awesome, awesome-lists
You can add more if you want.
Thanks to @redmusic27 we already have logo suggestions [here](https://github.com/rShetty/awesome-podcasts/issues/98), please select one and add to the repo

**Comment by rShetty** [comment]
@skat00sh Done, except for the logo.

**Comment by skat00sh** [comment]
@rShetty Great! I will generate a PR once you finalize the logo

**Comment by skat00sh** [comment]
@rShetty Did you finalize the logo?

**Comment by rShetty** [comment]
@skat00sh I am not particular of any one kind of logo. It would be amazing if you can help choose one and raise a PR 👍

**Comment by skat00sh** [comment]
@rShetty done 👍

**Comment by rShetty** [comment]
@skat00sh Thanks merged

**Comment by rShetty** [comment]
@skat00sh Are we good to raise a PR on the awesome awesome list ?

**Comment by skat00sh** [comment]
@rShetty Sorry I got busy last week. I have raised the PR 👍

**Comment by rShetty** [comment]
Thanks @skat00sh
