### ISSUE TITLE
Add Kernel Panic podcast

### ISSUE THREAD

**Issue by lZzozZl** [rShetty/awesome-podcasts#205]
https://www.kernelpanicpodcast.com/

Here is the url.
The guys who make the podcast are linux veterans, one of them made a lot of linux tutorials.
Thy are talking about news, problems and have some guests which tell their stories and stuff.
They are not very regular and episodes are ~1 hour long

**Comment by rShetty** [comment]
PR plz

**Comment by lZzozZl** [comment]
What PR stands for?

**Comment by rShetty** [comment]
Pull request

**Comment by Smoczysko** [comment]
@rShetty PR ready: https://github.com/rShetty/awesome-podcasts/pull/235
