### ISSUE TITLE
[Enhancement] Related Sass/hosted chat org

### ISSUE THREAD

**Issue by rorhug** [rShetty/awesome-podcasts#255]
#### idea, little effort part
Would be great to have slack / discord / telegram / x group for this. People could suggest and discuss these awesome podcasts.

### optional rule suggestions 
_/ opinionated setup (less than 30mins)_

- **#general**
  - For discussing podcasts mostly related to the topics listed in the readme
  - Silent for everyone (i believe discord allows this by default)
  - No links allowed
  - Max chars, maybe?
  - If it grows fast, possibly use separate channels for each topic...

### very much optional useful oss integration idea
_ongoing project OR a well selected, existing bot setup_

- **#podcasts**
  - Have the default channel when joining as a "podcast submission channel"
  - Paste a link to a podcast, people can up/down vote links with reactions (bot will add one up and one down on every link)
  - Long cooldown (time you must wait before you may send another)
  - Maybe start at an hour or two and increase as it gets busy + spammers arrive
  - Top podcasts that week get an automatic PR on GitHub from the bot
  - Admins could fix the categories or other meta data for the PR
  - For very popular sites, a `lib/sites` could contain unfurls. Open embed etc. for the rest.
  - With that setup, spam should be low and the best will get through
  - Another option would be to just submit to the bot... also any PRs opened maybe...
  - Pasting links in #general works within your global throttle.
  - Any re-posts / dupes could either be counted at the end of each week, votes summed. (or instead just suggest in the bot chat a link to the previous message to upvote)
  - edit: since realised that https://podhunt.app/ which "kind of" covers this part

**Comment by rShetty** [comment]
@rorhug Sounds good. Do you want to take a lead in setting this up?
