### ISSUE TITLE
[Suggestion] PHPugly

### ISSUE THREAD

**Issue by panigrc** [rShetty/awesome-podcasts#29]
Title: PHPUgly
Category: PHP
Website: https://phpugly.simplecast.fm/
Description: The podcast your mother warned you about. Ramblings of a few overworked PHP Developers.
Frequency: Weekly

**Comment by rShetty** [comment]
@panigrc  PR plz ?

**Comment by rShetty** [comment]
Added in #100, closing

**Comment by rShetty** [comment]
Thanks to @davidsouza
