### ISSUE TITLE
Greater than Code and perhaps a new category?

### ISSUE THREAD

**Issue by cmstead** [rShetty/awesome-podcasts#49]
This is a engineer-related podcast, but the focus is around humans working together.  I don't really think it fits under Agile, and might be a good fit if you had a category like "Community."

Anyway, I felt it would be weird to submit a totally new category without seeking feedback first.

Also, here's a link to the podcast in case you're interested:

https://www.greaterthancode.com/

**Comment by rShetty** [comment]
I think we can go ahead and create a new category. Please go ahead with PR. Thanks

**Comment by rShetty** [comment]
already added, closing
