### ISSUE TITLE
Add approximate runtimes

### ISSUE THREAD

**Issue by josh-green** [rShetty/awesome-podcasts#50]
A runtime would be good to have against each podcast. If they vary a lot between each episode an approximate range could be given?

**Comment by rShetty** [comment]
@josh-green Hey sorry, I am not completely clear on what you mean here

**Comment by rShetty** [comment]
@josh-green Can you raise a PR on this project plz ?

**Comment by josh-green** [comment]
Working through them now, I've done around 27 podcasts so far. It takes time to go back through the episodes to find their runtimes and get an average for them! Should be done in a day or so.

**Comment by rShetty** [comment]
@josh-green Thank you very much :)

**Comment by rShetty** [comment]
@josh-green Is there any progress on this ?
