### ISSUE TITLE
Add duration and hosts of the podcasts.

### ISSUE THREAD

**Issue by devdinu** [rShetty/awesome-podcasts#69]
duration could be on slabs ≈5m ≈30m ≈45m >1hr. 

Hosts with the link could be helpful to analyse the podcast and pick the interesting ones.

**Comment by rShetty** [comment]
@devdinu Can you help adding for some of the podcasts, Please feel free to raise a PR

**Comment by josh-green** [comment]
Duration should be covered under #50, but regular hosts is still a good suggestion.

**Comment by wireguy** [comment]
https://github.com/rShetty/awesome-podcasts/pull/203

Initial pass at adding Host: entry for all podcasts.
Included twitter links when available, because I thought that would be helpful.
Skipped podcasts with large 'panel' of speakers.

I think this issue can be marked closed.

**Comment by rShetty** [comment]
Cool thanks @wireguy. Very nicely done
