### ISSUE TITLE
Separate by the language

### ISSUE THREAD

**Issue by guar47** [rShetty/awesome-podcasts#74]
Hey guys! 
What do you think about separation podcasts by the language? I noticed you have Russian podcasts there, I could add them a lot, but it could be useless for people who didn't know the Russian language. I'm sure there are other language podcasts as well.
Thanks.

**Comment by rShetty** [comment]
@guar47 Yes I think it makes sense to separate it out. Please help with this by raising a PR. Thanks

**Comment by saitonakamura** [comment]
I've done the basic part here https://github.com/rShetty/awesome-podcasts/pull/104
