### ISSUE TITLE
[Suggestion] Chance the Developer

### ISSUE THREAD

**Issue by desirottman** [rShetty/awesome-podcasts#80]
https://chancethedev.com/ 

> hi! I’m Chance, a junior web developer and extra junior podcaster. I truly don’t know what I’m doing here, but my hope is to share what I’ve learned about this exciting and amazingly fun career of mine, and in the process I hope to learn a ton from you and the folks I encounter along the journey.

**Comment by rShetty** [comment]
Thanks @davidsouza Closing this #102
