### ISSUE TITLE
No inline HTML

### ISSUE THREAD

**Issue by BattleBas** [rShetty/awesome-podcasts#82]
Instead of using the HTML bold tag \<b\> I would recommend switching to using double asterisks **
This will promote using pure markdown syntax within the markdown file.

I don't mind making a pull request, but I would like your opinion before moving forward. Thank you!

Sources:
[Markdown cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

I stumbled on to this suggestion because of the markdown-lint extension in vscode, a more detailed description can be found here: https://github.com/updownpress/markdown-lint/blob/master/rules/033-no-inline-html.md

**Comment by rShetty** [comment]
@BattleBas I think it makes sense to be using markdown. Please go ahead and raise a PR. Thanks 👍

**Comment by BattleBas** [comment]
@guar47  awesome, I'll close this issue then.
