### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [rShetty/awesome-podcasts#98]
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by rShetty** [comment]
@redmusic27 Thanks, please go ahead with designs

**Comment by redmusic27** [comment]
Okay sir. I will start to make a logo for you. if it is ready I will be back

**Comment by redmusic27** [comment]
Hello sir, I have created a concept logo for you.  If you like it, I'll send you files and pr.
is there anything you want ?

![main](https://user-images.githubusercontent.com/37577374/38487384-21769e08-3c0a-11e8-9959-f02dc9965a66.jpg)
![main2](https://user-images.githubusercontent.com/37577374/38487507-9740413e-3c0a-11e8-8c10-43fe00817317.jpg)

**Comment by rShetty** [comment]
@redmusic27 The logos look pretty dope. Please go ahead and send a PR. Thanks

**Comment by rShetty** [comment]
Thanks @redmusic27. This is completed.
